-- 3. nationalities
CREATE TABLE nationalities (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ini_code VARCHAR(4) DEFAULT 'NATI',
    name VARCHAR(100) NOT NULL,
    iso_code VARCHAR(3) NOT NULL,
    flag_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
ALTER TABLE nationalities ENABLE ROW LEVEL SECURITY;

-- Data for nationalities (focused on Benelux and major hockey nations)
INSERT INTO nationalities (id, name, iso_code) VALUES
(gen_random_uuid(), 'Netherlands', 'NLD'),
(gen_random_uuid(), 'Belgium', 'BEL'),
(gen_random_uuid(), 'Luxembourg', 'LUX'),
(gen_random_uuid(), 'Canada', 'CAN'),
(gen_random_uuid(), 'United States', 'USA'),
(gen_random_uuid(), 'Sweden', 'SWE'),
(gen_random_uuid(), 'Finland', 'FIN'),
(gen_random_uuid(), 'Czech Republic', 'CZE'),
(gen_random_uuid(), 'Germany', 'DEU'),
(gen_random_uuid(), 'Switzerland', 'CHE'),
(gen_random_uuid(), 'Slovakia', 'SVK'),
(gen_random_uuid(), 'Russia', 'RUS'),
(gen_random_uuid(), 'Latvia', 'LVA');

INSERT INTO nationalities (id, name, iso_code) VALUES
(gen_random_uuid(), 'Austria', 'AUT'),
(gen_random_uuid(), 'Denmark', 'DNK'),
(gen_random_uuid(), 'France', 'FRA'),
(gen_random_uuid(), 'Norway', 'NOR'),
(gen_random_uuid(), 'Great Britain', 'GBR'),
(gen_random_uuid(), 'Kazakhstan', 'KAZ'),
(gen_random_uuid(), 'Belarus', 'BLR'),
(gen_random_uuid(), 'Italy', 'ITA'),
(gen_random_uuid(), 'Slovenia', 'SVN'),
(gen_random_uuid(), 'Hungary', 'HUN'),
(gen_random_uuid(), 'Poland', 'POL'),
(gen_random_uuid(), 'Japan', 'JPN'),
(gen_random_uuid(), 'Ukraine', 'UKR'),
(gen_random_uuid(), 'South Korea', 'KOR'),
(gen_random_uuid(), 'China', 'CHN'),
(gen_random_uuid(), 'Romania', 'ROU'),
(gen_random_uuid(), 'Lithuania', 'LTU'),
(gen_random_uuid(), 'Estonia', 'EST');

INSERT INTO nationalities (id, name, iso_code) VALUES
(gen_random_uuid(), 'Aruba', 'ABW'),
(gen_random_uuid(), 'Afghanistan', 'AFG'),
(gen_random_uuid(), 'Angola', 'AGO'),
(gen_random_uuid(), 'Anguilla', 'AIA'),
(gen_random_uuid(), 'Åland Islands', 'ALA'),
(gen_random_uuid(), 'Albania', 'ALB'),
(gen_random_uuid(), 'Andorra', 'AND'),
(gen_random_uuid(), 'United Arab Emirates', 'ARE'),
(gen_random_uuid(), 'Argentina', 'ARG'),
(gen_random_uuid(), 'Armenia', 'ARM'),
(gen_random_uuid(), 'American Samoa', 'ASM'),
(gen_random_uuid(), 'Antarctica', 'ATA'),
(gen_random_uuid(), 'French Southern Territories', 'ATF'),
(gen_random_uuid(), 'Antigua and Barbuda', 'ATG'),
(gen_random_uuid(), 'Australia', 'AUS'),
(gen_random_uuid(), 'Azerbaijan', 'AZE'),
(gen_random_uuid(), 'Burundi', 'BDI'),
(gen_random_uuid(), 'Benin', 'BEN'),
(gen_random_uuid(), 'Bonaire, Sint Eustatius and Saba', 'BES'),
(gen_random_uuid(), 'Burkina Faso', 'BFA'),
(gen_random_uuid(), 'Bangladesh', 'BGD'),
(gen_random_uuid(), 'Bulgaria', 'BGR'),
(gen_random_uuid(), 'Bahrain', 'BHR'),
(gen_random_uuid(), 'Bahamas', 'BHS'),
(gen_random_uuid(), 'Bosnia and Herzegovina', 'BIH'),
(gen_random_uuid(), 'Saint Barthélemy', 'BLM'),
(gen_random_uuid(), 'Belize', 'BLZ'),
(gen_random_uuid(), 'Bermuda', 'BMU'),
(gen_random_uuid(), 'Bolivia, Plurinational State of', 'BOL'),
(gen_random_uuid(), 'Brazil', 'BRA'),
(gen_random_uuid(), 'Barbados', 'BRB'),
(gen_random_uuid(), 'Brunei Darussalam', 'BRN'),
(gen_random_uuid(), 'Bhutan', 'BTN'),
(gen_random_uuid(), 'Bouvet Island', 'BVT'),
(gen_random_uuid(), 'Botswana', 'BWA'),
(gen_random_uuid(), 'Central African Republic', 'CAF'),
(gen_random_uuid(), 'Cocos (Keeling) Islands', 'CCK'),
(gen_random_uuid(), 'Chile', 'CHL'),
(gen_random_uuid(), 'Côte d''Ivoire', 'CIV'),
(gen_random_uuid(), 'Cameroon', 'CMR'),
(gen_random_uuid(), 'Congo, The Democratic Republic of the', 'COD'),
(gen_random_uuid(), 'Congo', 'COG'),
(gen_random_uuid(), 'Cook Islands', 'COK'),
(gen_random_uuid(), 'Colombia', 'COL'),
(gen_random_uuid(), 'Comoros', 'COM'),
(gen_random_uuid(), 'Cabo Verde', 'CPV'),
(gen_random_uuid(), 'Costa Rica', 'CRI'),
(gen_random_uuid(), 'Cuba', 'CUB'),
(gen_random_uuid(), 'Curaçao', 'CUW'),
(gen_random_uuid(), 'Christmas Island', 'CXR'),
(gen_random_uuid(), 'Cayman Islands', 'CYM'),
(gen_random_uuid(), 'Cyprus', 'CYP'),
(gen_random_uuid(), 'Djibouti', 'DJI'),
(gen_random_uuid(), 'Dominica', 'DMA'),
(gen_random_uuid(), 'Dominican Republic', 'DOM'),
(gen_random_uuid(), 'Algeria', 'DZA'),
(gen_random_uuid(), 'Ecuador', 'ECU'),
(gen_random_uuid(), 'Egypt', 'EGY'),
(gen_random_uuid(), 'Eritrea', 'ERI'),
(gen_random_uuid(), 'Western Sahara', 'ESH'),
(gen_random_uuid(), 'Spain', 'ESP'),
(gen_random_uuid(), 'Ethiopia', 'ETH'),
(gen_random_uuid(), 'Fiji', 'FJI'),
(gen_random_uuid(), 'Falkland Islands (Malvinas)', 'FLK'),
(gen_random_uuid(), 'Faroe Islands', 'FRO'),
(gen_random_uuid(), 'Micronesia, Federated States of', 'FSM'),
(gen_random_uuid(), 'Gabon', 'GAB'),
(gen_random_uuid(), 'Georgia', 'GEO'),
(gen_random_uuid(), 'Guernsey', 'GGY'),
(gen_random_uuid(), 'Ghana', 'GHA'),
(gen_random_uuid(), 'Gibraltar', 'GIB'),
(gen_random_uuid(), 'Guinea', 'GIN'),
(gen_random_uuid(), 'Guadeloupe', 'GLP'),
(gen_random_uuid(), 'Gambia', 'GMB'),
(gen_random_uuid(), 'Guinea-Bissau', 'GNB'),
(gen_random_uuid(), 'Equatorial Guinea', 'GNQ'),
(gen_random_uuid(), 'Greece', 'GRC'),
(gen_random_uuid(), 'Grenada', 'GRD'),
(gen_random_uuid(), 'Greenland', 'GRL'),
(gen_random_uuid(), 'Guatemala', 'GTM'),
(gen_random_uuid(), 'French Guiana', 'GUF'),
(gen_random_uuid(), 'Guam', 'GUM'),
(gen_random_uuid(), 'Guyana', 'GUY'),
(gen_random_uuid(), 'Hong Kong', 'HKG'),
(gen_random_uuid(), 'Heard Island and McDonald Islands', 'HMD'),
(gen_random_uuid(), 'Honduras', 'HND'),
(gen_random_uuid(), 'Croatia', 'HRV'),
(gen_random_uuid(), 'Haiti', 'HTI'),
(gen_random_uuid(), 'Indonesia', 'IDN'),
(gen_random_uuid(), 'Isle of Man', 'IMN'),
(gen_random_uuid(), 'India', 'IND'),
(gen_random_uuid(), 'British Indian Ocean Territory', 'IOT'),
(gen_random_uuid(), 'Ireland', 'IRL'),
(gen_random_uuid(), 'Iran, Islamic Republic of', 'IRN'),
(gen_random_uuid(), 'Iraq', 'IRQ'),
(gen_random_uuid(), 'Iceland', 'ISL'),
(gen_random_uuid(), 'Israel', 'ISR'),
(gen_random_uuid(), 'Jamaica', 'JAM'),
(gen_random_uuid(), 'Jersey', 'JEY'),
(gen_random_uuid(), 'Jordan', 'JOR'),
(gen_random_uuid(), 'Kenya', 'KEN'),
(gen_random_uuid(), 'Kyrgyzstan', 'KGZ'),
(gen_random_uuid(), 'Cambodia', 'KHM'),
(gen_random_uuid(), 'Kiribati', 'KIR'),
(gen_random_uuid(), 'Saint Kitts and Nevis', 'KNA'),
(gen_random_uuid(), 'Kuwait', 'KWT'),
(gen_random_uuid(), 'Lao People''s Democratic Republic', 'LAO'),
(gen_random_uuid(), 'Lebanon', 'LBN'),
(gen_random_uuid(), 'Liberia', 'LBR'),
(gen_random_uuid(), 'Libya', 'LBY'),
(gen_random_uuid(), 'Saint Lucia', 'LCA'),
(gen_random_uuid(), 'Liechtenstein', 'LIE'),
(gen_random_uuid(), 'Sri Lanka', 'LKA'),
(gen_random_uuid(), 'Lesotho', 'LSO'),
(gen_random_uuid(), 'Macao', 'MAC'),
(gen_random_uuid(), 'Saint Martin (French part)', 'MAF'),
(gen_random_uuid(), 'Morocco', 'MAR'),
(gen_random_uuid(), 'Monaco', 'MCO'),
(gen_random_uuid(), 'Moldova, Republic of', 'MDA'),
(gen_random_uuid(), 'Madagascar', 'MDG'),
(gen_random_uuid(), 'Maldives', 'MDV'),
(gen_random_uuid(), 'Mexico', 'MEX'),
(gen_random_uuid(), 'Marshall Islands', 'MHL'),
(gen_random_uuid(), 'North Macedonia', 'MKD'),
(gen_random_uuid(), 'Mali', 'MLI'),
(gen_random_uuid(), 'Malta', 'MLT'),
(gen_random_uuid(), 'Myanmar', 'MMR'),
(gen_random_uuid(), 'Montenegro', 'MNE'),
(gen_random_uuid(), 'Mongolia', 'MNG'),
(gen_random_uuid(), 'Northern Mariana Islands', 'MNP'),
(gen_random_uuid(), 'Mozambique', 'MOZ'),
(gen_random_uuid(), 'Mauritania', 'MRT'),
(gen_random_uuid(), 'Montserrat', 'MSR'),
(gen_random_uuid(), 'Martinique', 'MTQ'),
(gen_random_uuid(), 'Mauritius', 'MUS'),
(gen_random_uuid(), 'Malawi', 'MWI'),
(gen_random_uuid(), 'Malaysia', 'MYS'),
(gen_random_uuid(), 'Mayotte', 'MYT'),
(gen_random_uuid(), 'Namibia', 'NAM'),
(gen_random_uuid(), 'New Caledonia', 'NCL'),
(gen_random_uuid(), 'Niger', 'NER'),
(gen_random_uuid(), 'Norfolk Island', 'NFK'),
(gen_random_uuid(), 'Nigeria', 'NGA'),
(gen_random_uuid(), 'Nicaragua', 'NIC'),
(gen_random_uuid(), 'Niue', 'NIU'),
(gen_random_uuid(), 'Nepal', 'NPL'),
(gen_random_uuid(), 'Nauru', 'NRU'),
(gen_random_uuid(), 'New Zealand', 'NZL'),
(gen_random_uuid(), 'Oman', 'OMN'),
(gen_random_uuid(), 'Pakistan', 'PAK'),
(gen_random_uuid(), 'Panama', 'PAN'),
(gen_random_uuid(), 'Pitcairn', 'PCN'),
(gen_random_uuid(), 'Peru', 'PER'),
(gen_random_uuid(), 'Philippines', 'PHL'),
(gen_random_uuid(), 'Palau', 'PLW'),
(gen_random_uuid(), 'Papua New Guinea', 'PNG'),
(gen_random_uuid(), 'Puerto Rico', 'PRI'),
(gen_random_uuid(), 'Korea, Democratic People''s Republic of', 'PRK'),
(gen_random_uuid(), 'Portugal', 'PRT'),
(gen_random_uuid(), 'Paraguay', 'PRY'),
(gen_random_uuid(), 'Palestine, State of', 'PSE'),
(gen_random_uuid(), 'French Polynesia', 'PYF'),
(gen_random_uuid(), 'Qatar', 'QAT'),
(gen_random_uuid(), 'Réunion', 'REU'),
(gen_random_uuid(), 'Rwanda', 'RWA'),
(gen_random_uuid(), 'Saudi Arabia', 'SAU'),
(gen_random_uuid(), 'Sudan', 'SDN'),
(gen_random_uuid(), 'Senegal', 'SEN'),
(gen_random_uuid(), 'Singapore', 'SGP'),
(gen_random_uuid(), 'South Georgia and the South Sandwich Islands', 'SGS'),
(gen_random_uuid(), 'Saint Helena, Ascension and Tristan da Cunha', 'SHN'),
(gen_random_uuid(), 'Svalbard and Jan Mayen', 'SJM'),
(gen_random_uuid(), 'Solomon Islands', 'SLB'),
(gen_random_uuid(), 'Sierra Leone', 'SLE'),
(gen_random_uuid(), 'El Salvador', 'SLV'),
(gen_random_uuid(), 'San Marino', 'SMR'),
(gen_random_uuid(), 'Somalia', 'SOM'),
(gen_random_uuid(), 'Saint Pierre and Miquelon', 'SPM'),
(gen_random_uuid(), 'Serbia', 'SRB'),
(gen_random_uuid(), 'South Sudan', 'SSD'),
(gen_random_uuid(), 'Sao Tome and Principe', 'STP'),
(gen_random_uuid(), 'Suriname', 'SUR'),
(gen_random_uuid(), 'Eswatini', 'SWZ'),
(gen_random_uuid(), 'Sint Maarten (Dutch part)', 'SXM'),
(gen_random_uuid(), 'Seychelles', 'SYC'),
(gen_random_uuid(), 'Syrian Arab Republic', 'SYR'),
(gen_random_uuid(), 'Turks and Caicos Islands', 'TCA'),
(gen_random_uuid(), 'Chad', 'TCD'),
(gen_random_uuid(), 'Togo', 'TGO'),
(gen_random_uuid(), 'Thailand', 'THA'),
(gen_random_uuid(), 'Tajikistan', 'TJK'),
(gen_random_uuid(), 'Tokelau', 'TKL'),
(gen_random_uuid(), 'Turkmenistan', 'TKM'),
(gen_random_uuid(), 'Timor-Leste', 'TLS'),
(gen_random_uuid(), 'Tonga', 'TON'),
(gen_random_uuid(), 'Trinidad and Tobago', 'TTO'),
(gen_random_uuid(), 'Tunisia', 'TUN'),
(gen_random_uuid(), 'Türkiye', 'TUR'),
(gen_random_uuid(), 'Tuvalu', 'TUV'),
(gen_random_uuid(), 'Taiwan, Province of China', 'TWN'),
(gen_random_uuid(), 'Tanzania, United Republic of', 'TZA'),
(gen_random_uuid(), 'Uganda', 'UGA'),
(gen_random_uuid(), 'United States Minor Outlying Islands', 'UMI'),
(gen_random_uuid(), 'Uruguay', 'URY'),
(gen_random_uuid(), 'Uzbekistan', 'UZB'),
(gen_random_uuid(), 'Holy See (Vatican City State)', 'VAT'),
(gen_random_uuid(), 'Saint Vincent and the Grenadines', 'VCT'),
(gen_random_uuid(), 'Venezuela, Bolivarian Republic of', 'VEN'),
(gen_random_uuid(), 'Virgin Islands, British', 'VGB'),
(gen_random_uuid(), 'Virgin Islands, U.S.', 'VIR'),
(gen_random_uuid(), 'Viet Nam', 'VNM'),
(gen_random_uuid(), 'Vanuatu', 'VUT'),
(gen_random_uuid(), 'Wallis and Futuna', 'WLF'),
(gen_random_uuid(), 'Samoa', 'WSM'),
(gen_random_uuid(), 'Yemen', 'YEM'),
(gen_random_uuid(), 'South Africa', 'ZAF'),
(gen_random_uuid(), 'Zambia', 'ZMB'),
(gen_random_uuid(), 'Zimbabwe', 'ZWE');
