-- 9. player_attributes
CREATE TABLE player_attributes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ini_code VARCHAR(4) DEFAULT 'PLAT',
    player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    -- Goaltending
    blocker INTEGER CHECK (blocker BETWEEN 1 AND 100),
    glove INTEGER CHECK (glove BETWEEN 1 AND 100),
    one_on_ones INTEGER CHECK (one_on_ones BETWEEN 1 AND 100),
    rebounds INTEGER CHECK (rebounds BETWEEN 1 AND 100),
    recovery INTEGER CHECK (recovery BETWEEN 1 AND 100),
    reflexes INTEGER CHECK (reflexes BETWEEN 1 AND 100),
    -- Mental
    aggression INTEGER CHECK (aggression BETWEEN 1 AND 100),
    agitation INTEGER CHECK (agitation BETWEEN 1 AND 100),
    anticipation INTEGER CHECK (anticipation BETWEEN 1 AND 100),
    bravery INTEGER CHECK (bravery BETWEEN 1 AND 100),
    consistency INTEGER CHECK (consistency BETWEEN 1 AND 100),
    creativity INTEGER CHECK (creativity BETWEEN 1 AND 100),
    decisions INTEGER CHECK (decisions BETWEEN 1 AND 100),
    dirtiness INTEGER CHECK (dirtiness BETWEEN 1 AND 100),
    flair INTEGER CHECK (flair BETWEEN 1 AND 100),
    important_matches INTEGER CHECK (important_matches BETWEEN 1 AND 100),
    leadership INTEGER CHECK (leadership BETWEEN 1 AND 100),
    morale INTEGER CHECK (morale BETWEEN 1 AND 100),
    pass_tendency INTEGER CHECK (pass_tendency BETWEEN 1 AND 100),
    teamwork INTEGER CHECK (teamwork BETWEEN 1 AND 100),
    versatility INTEGER CHECK (versatility BETWEEN 1 AND 100),
    work_rate INTEGER CHECK (work_rate BETWEEN 1 AND 100),
    -- Physical
    acceleration INTEGER CHECK (acceleration BETWEEN 1 AND 100),
    agility INTEGER CHECK (agility BETWEEN 1 AND 100),
    balance INTEGER CHECK (balance BETWEEN 1 AND 100),
    injury_proneness INTEGER CHECK (injury_proneness BETWEEN 1 AND 100),
    natural_fitness INTEGER CHECK (natural_fitness BETWEEN 1 AND 100),
    pace INTEGER CHECK (pace BETWEEN 1 AND 100),
    stamina INTEGER CHECK (stamina BETWEEN 1 AND 100),
    strength INTEGER CHECK (strength BETWEEN 1 AND 100),
    -- Technical
    checking INTEGER CHECK (checking BETWEEN 1 AND 100),
    deflections INTEGER CHECK (deflections BETWEEN 1 AND 100),
    deking INTEGER CHECK (deking BETWEEN 1 AND 100),
    faceoffs INTEGER CHECK (faceoffs BETWEEN 1 AND 100),
    fighting INTEGER CHECK (fighting BETWEEN 1 AND 100),
    hitting INTEGER CHECK (hitting BETWEEN 1 AND 100),
    movement INTEGER CHECK (movement BETWEEN 1 AND 100),
    passing INTEGER CHECK (passing BETWEEN 1 AND 100),
    pokecheck INTEGER CHECK (pokecheck BETWEEN 1 AND 100),
    positioning INTEGER CHECK (positioning BETWEEN 1 AND 100),
    slapshot INTEGER CHECK (slapshot BETWEEN 1 AND 100),
    stickhandling INTEGER CHECK (stickhandling BETWEEN 1 AND 100),
    wristshot INTEGER CHECK (wristshot BETWEEN 1 AND 100),
    evaluated_date DATE,
    evaluator_id UUID REFERENCES staff(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
ALTER TABLE player_attributes ENABLE ROW LEVEL SECURITY;
