-- stick_curves.sql
CREATE TABLE stick_curves (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ini_code VARCHAR(4) DEFAULT 'CURV',
    cdn_url TEXT,
    curve VARCHAR(50) NOT NULL,
    curve_name VARCHAR(100),
    moq INTEGER,
    is_common BOOLEAN DEFAULT FALSE,
    is_beginner_friendly BOOLEAN DEFAULT FALSE,
    best_for TEXT,
    variant VARCHAR(50),
    series VARCHAR(50),
    length_mm NUMERIC(5, 1),
    height_mm NUMERIC(5, 1),
    face_curve_mm NUMERIC(5, 1),
    lie NUMERIC(5, 1),
    open_heel_mm NUMERIC(5, 1),
    mid_mm NUMERIC(5, 1),
    toe_opening_degrees NUMERIC(5, 1),
    similar_curve_1 VARCHAR(50),
    similar_curve_2 VARCHAR(50),
    similar_curve_3 VARCHAR(50),
    equivalent_1 VARCHAR(100),
    equivalent_2 VARCHAR(100),
    equivalent_3 VARCHAR(100),
    equivalent_4 VARCHAR(100),
    equivalent_5 VARCHAR(100),
    equivalent_6 VARCHAR(100),
    equivalent_7 VARCHAR(100),
    equivalent_8 VARCHAR(100),
    equivalent_9 VARCHAR(100),
    equivalent_10 VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
ALTER TABLE stick_curves ENABLE ROW LEVEL SECURITY;
